
@startuml
start

:forgot password(phoneNumber);
if (Такий користувач існує?) then (Так)
  :Надсилаємо SMS-код;
  :Переходимо на сторінку відновлення паролю ;
  :Вводимо дані для відновлення паролю (phoneNumber, smsCode, password, password);
  if (SMS-код коректний і пароль валідний ?) then (Так)
     :Отримуємо Auth Token і дані користувача;
     :Переходимо на головну сторінку користувача;
     stop;
  else (Ні)
    :Висвітлюємо помилку;
  endif
else (Ні)
  :Висвітлюємо помилку;
endif


@enduml
