spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://admin:admin@cluster0.ilb0w.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
    rest:
      detection-strategy: annotated
      return-body-on-create: true
      return-body-on-update: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
twilio:
  accountSid: ${TWILIO_SID}
  authToken: ${TWILIO_TOKEN}
  serviceId: ${TWILIO_ID}

server:
  port: ${PORT:8080}
