spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD:admin}@cluster0.ilb0w.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
    rest:
      detection-strategy: annotated
      return-body-on-create: true
      return-body-on-update: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
twilio:
  accountSid: ${TWILIO_SID:AC3a95b14e95eca5575e7561f77048dd28}
  authToken: ${TWILIO_TOKEN:f139a7d3ad58b3d04faa20605aef04a4}
  serviceId: ${TWILIO_ID:MG3e36836ec02e7b7d6cc7daf5e12e0d81}

server:
  port: ${PORT:8080}
