spring:
  social:
    facebook:
      app-id: 498747050475693
      app-secret: fca6b3fedcbd6b35c0b692b3d084b7a8
      page:
        accessToken: EAAHFm5jGwK0BABBgxxPtRgO0hqFzSDCR4KKgkrgTcYLmqTLy7JZCnmJDpZB5163HPYZA7QrZAHXJBbMHFuDAtEkyol2I7fKXbfp3UgBxgKbqtznZADwZBZCZB8ZCqoMSaznbDbi63bAoW9QCkvvbkwKupimnS16Upx9BjMxwrUrAuwQZDZD
  data:
    mongodb:
#      host: mongo
      uri: mongodb+srv://mtust:admin@cluster0.ilb0w.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
#      host: 127.0.0.1
#      port: 27017
#      dbname: taxi
    rest:
      detection-strategy: annotated
      return-body-on-create: true
      return-body-on-update: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://db:5432/test
#    url: jdbc:postgresql://localhost:5432/test
#    username: postgres
#    password: rootgresql://localhost:5432/test
    url: jdbc:postgresql://35.238.112.31:5432/test
    username: postgres
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 121189305185277
            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # Note that facebook now mandates the use of https redirect URIs, so make sure your app supports https in production
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

messenger4j:
  verifyToken: token

google:
  map:
    api:
      key: AIzaSyACkjaKFrlx1-q-mzKzUISJik7DskFEstw

server:
  port: 8080

