spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@cluster0.ilb0w.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
    rest:
      detection-strategy: annotated
      return-body-on-create: true
      return-body-on-update: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
twilio:
  accountSid: ${TWILIO_SID}
  authToken: ${TWILIO_TOKEN}
  serviceId: ${TWILIO_ID}

server:
  port: ${PORT:8080}
#
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html

