spring:
  data:
    mongodb:
      auto-index-creation: true
#      host: mongo
      uri: mongodb+srv://mtust:admin@cluster0.ilb0w.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
#      host: 127.0.0.1
#      port: 27017
#      dbname: taxi
    rest:
      detection-strategy: annotated
      return-body-on-create: true
      return-body-on-update: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
twilio:
  accountSid: AC3a95b14e95eca5575e7561f77048dd28
  authToken: 6ca5374995f83639f269118d43299ade
  serviceId: MG3e36836ec02e7b7d6cc7daf5e12e0d81

server:
  port: ${PORT:8080}
#
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html

