name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: taxiproject
      PROJECT_ID: taxiproject-209815

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      # Authenticate Docker with Google Cloud
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      # Build Docker Image with Secrets
      - name: Build Docker Image
        env:
          DB_URI: ${{ secrets.DB_URI }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_ID: ${{ secrets.TWILIO_ID }}
        run: |
          docker build \
            --build-arg DB_URI=${DB_URI} \
            --build-arg DB_USER=${DB_USER} \
            --build-arg DB_PASSWORD=${DB_PASSWORD} \
            --build-arg TWILIO_SID=${TWILIO_SID} \
            --build-arg TWILIO_TOKEN=${TWILIO_TOKEN} \
            --build-arg TWILIO_ID=${TWILIO_ID} \
            -t gcr.io/$PROJECT_ID/$IMAGE_NAME:latest .

      # Push Docker Image to Google Container Registry
      - name: Push Docker Image to Google Container Registry
        run: docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      # Deploy to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy taxirun \
          --image gcr.io/$PROJECT_ID/$IMAGE_NAME:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --project $PROJECT_ID \
          --set-env-vars DB_URI=${{ secrets.DB_URI }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},TWILIO_SID=${{ secrets.TWILIO_SID }},TWILIO_TOKEN=${{ secrets.TWILIO_TOKEN }},TWILIO_ID=${{ secrets.TWILIO_ID }}
