---
name: Build and Push Java Image to Google Cloud Run
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: taxiproject
      PROJECT_ID: taxiproject-209815
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          service_account_email: mtustanovskyy@gmail.com
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:latest/run-sql .

      - name: Push
        run: |
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      - name: Deploy
        run: |
          gcloud run deploy helloworld \
          --region us-central1 \
          --image gcr.io/$PROJECT_ID/$IMAGE_NAME \
          --add-cloudsql-instances="taxiproject-209815:us-central1:taxiproject" \
          --set-env-vars DB_NAME="quickstart-db" \
          --set-env-vars DB_USER="postgresql" \
          --set-env-vars DB_PASS="admin" \
          --set-env-vars DB_PORT="5432"\ 
          --platform managed \
          --allow-unauthenticated \
          --project $PROJECT_ID 
