name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: taxiproject
      PROJECT_ID: taxiproject-209815

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" > "${HOME}/gcloud-service-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcloud-service-key.json"
          gcloud auth configure-docker

      - name: Build Docker Image
        env:
          DB_URI: ${{ secrets.DB_URI }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_ID: ${{ secrets.TWILIO_ID }}
        run: |
          docker build \
            --build-arg DB_URI=${DB_URI} \
            --build-arg DB_USER=${DB_USER} \
            --build-arg DB_PASSWORD=${DB_PASSWORD} \
            --build-arg TWILIO_SID=${TWILIO_SID} \
            --build-arg TWILIO_TOKEN=${TWILIO_TOKEN} \
            --build-arg TWILIO_ID=${TWILIO_ID} \
            -t gcr.io/$PROJECT_ID/$IMAGE_NAME:latest .

      - name: Push Docker Image
        run: docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy taxirun \
          --image gcr.io/$PROJECT_ID/$IMAGE_NAME:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --project $PROJECT_ID \
          --set-env-vars DB_URI=${{ secrets.DB_URI }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},TWILIO_SID=${{ secrets.TWILIO_SID }},TWILIO_TOKEN=${{ secrets.TWILIO_TOKEN }},TWILIO_ID=${{ secrets.TWILIO_ID }}
