---
name: Build and Push Java Image to Google Cloud Run
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: taxiproject
      PROJECT_ID: taxiproject-209815
    steps:

      - name: Checkout
        uses: actions/checkout@v0

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: mtustanovskyy@gmail.com
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:latest .

      - name: Push
        run: |
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      - name: Deploy
        run: |
          gcloud run deploy helloworld \
          --region europe-west1 \
          --image gcr.io/$$PROJECT_ID/helloworld \
          --platform managed \
          --allow-unauthenticated \
          --project $$PROJECT_ID
