---
name: Build and Push Java Image to Google Cloud Run
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: taxiproject
      PROJECT_ID: taxiproject-209815
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          service_account_email: ${{variables.ACCOUNT_EMAIL}}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        env:
          DB_URI: ${{ secrets.DB_URI }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_ID: ${{ secrets.TWILIO_ID }}
        run: |
          docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:latest .

      - name: Push
        run: |
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      - name: Deploy
        run: |
          gcloud run deploy taxirun \
          --region us-central1 \
          --image gcr.io/$PROJECT_ID/$IMAGE_NAME \
          --platform managed \
          --allow-unauthenticated \
          --project $PROJECT_ID 
